### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sholland-bamboohealth** [0xC0000054/pdn-gmic#3]
Using paint.net 5.0.7 (Stable 5.7.8575.34822 on windows 10

`C:\Program Files\paint.net\Effects\Gmic.dll, version 3.3.1.0

System.IO.FileNotFoundException: Could not load file or assembly 'PaintDotNet.Effects.Core, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'PaintDotNet.Effects.Core, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'PaintDotNet.Effects.Core, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'PaintDotNet.Effects.Core, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at PaintDotNet.Runtime.Loader.TrustedPlatformAssemblyResolver.Load(ILoadContext loadContext, AssemblyName assemblyName, String assemblyPath) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\TrustedPlatformAssemblyResolver.cs:line 129
   at PaintDotNet.Runtime.Loader.CombinedAssemblyLoader.Load(ILoadContext loadContext, AssemblyName assemblyName, String assemblyPath) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\CombinedAssemblyLoader.cs:line 51
   at PaintDotNet.Runtime.Loader.LoadContext.AssemblyLoadContextImpl.Load(AssemblyName assemblyName) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\LoadContext.cs:line 168
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

System.IO.FileNotFoundException: Could not load file or assembly 'PaintDotNet.ComponentModel, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'PaintDotNet.ComponentModel, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'PaintDotNet.ComponentModel, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'PaintDotNet.ComponentModel, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at PaintDotNet.Runtime.Loader.TrustedPlatformAssemblyResolver.Load(ILoadContext loadContext, AssemblyName assemblyName, String assemblyPath) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\TrustedPlatformAssemblyResolver.cs:line 129
   at PaintDotNet.Runtime.Loader.CombinedAssemblyLoader.Load(ILoadContext loadContext, AssemblyName assemblyName, String assemblyPath) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\CombinedAssemblyLoader.cs:line 51
   at PaintDotNet.Runtime.Loader.LoadContext.AssemblyLoadContextImpl.Load(AssemblyName assemblyName) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\LoadContext.cs:line 168
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

System.IO.FileNotFoundException: Could not load file or assembly 'PaintDotNet.Primitives, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'PaintDotNet.Primitives, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'PaintDotNet.Primitives, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'PaintDotNet.Primitives, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at PaintDotNet.Runtime.Loader.TrustedPlatformAssemblyResolver.Load(ILoadContext loadContext, AssemblyName assemblyName, String assemblyPath) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\TrustedPlatformAssemblyResolver.cs:line 129
   at PaintDotNet.Runtime.Loader.CombinedAssemblyLoader.Load(ILoadContext loadContext, AssemblyName assemblyName, String assemblyPath) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\CombinedAssemblyLoader.cs:line 51
   at PaintDotNet.Runtime.Loader.LoadContext.AssemblyLoadContextImpl.Load(AssemblyName assemblyName) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\LoadContext.cs:line 168
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

System.IO.FileNotFoundException: Could not load file or assembly 'PaintDotNet.Core, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'PaintDotNet.Core, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'PaintDotNet.Core, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'PaintDotNet.Core, Version=5.11.8685.3093, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at PaintDotNet.Runtime.Loader.TrustedPlatformAssemblyResolver.Load(ILoadContext loadContext, AssemblyName assemblyName, String assemblyPath) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\TrustedPlatformAssemblyResolver.cs:line 129
   at PaintDotNet.Runtime.Loader.CombinedAssemblyLoader.Load(ILoadContext loadContext, AssemblyName assemblyName, String assemblyPath) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\CombinedAssemblyLoader.cs:line 51
   at PaintDotNet.Runtime.Loader.LoadContext.AssemblyLoadContextImpl.Load(AssemblyName assemblyName) in D:\src\pdn\src\PaintDotNet\Runtime\Loader\LoadContext.cs:line 168
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
`

**Comment by 0xC0000054** [comment]
Your Paint.NET version is out of date. You are using version 5.0.7, and the plugin requires 5.0.11.
